name: Dev - Build Docker Image & Push Image to Azure

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  REGISTRY: "acrwe564.azurecr.io"
  APP_NAME: we564-frontend
  IMAGE_TAG: "0.0.1-SNAPSHOT"
  REPOSITORY: "supernarubat1/we564-pipeline"
  EVENT_TYPE: "we564-frontend-cd-dev"

jobs:
  unitest:
    name: Unitest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run unitest
        run: npm run test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Unit Test Results
          path: "${{ github.workspace }}/coverage/lcov-report/*"

  analyze:
    name: SAST CodeQL-Build
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [unitest, analyze]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Docker Build Image & Push Image to Azure
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ env.REPOSITORY }}
          event-type: ${{ env.EVENT_TYPE }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
